_wandb:
    value:
        cli_version: 0.19.8
        code_path: code/cleanrl_nematic.py
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 35
                - 55
            "4": 3.12.7
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
anneal_lr:
    value: false
batch_size:
    value: 256
capture_video:
    value: false
clip_coef:
    value: 0.2
clip_vloss:
    value: true
cuda:
    value: true
ent_coef:
    value: 0
env_id:
    value: cupss
exp_name:
    value: cleanrl_nematic
gae_lambda:
    value: 0.95
gamma:
    value: 0.97
hf_entity:
    value: ""
learning_rate:
    value: 0.0001
max_grad_norm:
    value: 0.5
minibatch_size:
    value: 128
nematic_size:
    value:
        - 128
        - 128
norm_adv:
    value: true
num_envs:
    value: 1
num_iterations:
    value: 195
num_minibatches:
    value: 2
num_steps:
    value: 256
rmode:
    value: human
save_model:
    value: true
seed:
    value: 1
sname:
    value: /home/aaveg/projects/nematic2D/RL/nematic2D_pbc.cu
target_kl:
    value: null
torch_deterministic:
    value: true
total_timesteps:
    value: 50000
track:
    value: true
update_epochs:
    value: 5
upload_model:
    value: false
vf_coef:
    value: 0.5
wandb_entity:
    value: null
wandb_project_name:
    value: RL_project_m16
